// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetProfile():Promise<main.Profile>;

export function GetRegistryData():Promise<main.RegistryData>;
